news_app/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('pages.urls')),
    path('polls/', include('polls.urls')),
    path('notebook/', include('notebook.urls')),
    path('admin/', admin.site.urls),
]

notebook/urls.py
from django.urls import path
from . import views

app_name = 'notebook'
urlpatterns = [
    path('', views.index, name='index'),
]

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'
urlpatterns = [
    path('', views.index, name='index'),
]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

notebook/models.py
from django.db import models

# Create your models here.
class ContactType(models.Model):
    contact_type = models.CharField(max_length=100)

    def __str__(self):
        return self.contact_type

class Contact(models.Model):
    c_type = models.ForeignKey(ContactType, on_delete=models.CASCADE)
    contact_name = models.CharField(max_length=100)
    register_date = models.DateTimeField('date added')

    def __str__(self):
        return self.contact_name

        

pages/models.py
from django.db import models

# Create your models here.

polls/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text
        

posts/models.py
from django.db import models

# Create your models here.

notebook/views.py
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404 ,render
from django.urls import reverse

from .models import Contact, ContactType
#Get Contacts and disply them
def index(request):
    contacts_list = Contact.objects.order_by('contact_name')[:10]
    context = {'contacts_list': contacts_list}
    return render(request, 'notebook/index.html', context)

#
def detail(request, contact_id):
    try:
        contact = Contact.objects.get(pk=contact_id)
    except Contact.DoesNotExist:
        raise Http404('Contact does not exists')
    return render(request, 'notebook/detail.html', { 'contact' : contact})

pages/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'pages/index.html')

polls/views.py
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404 ,render
from django.urls import reverse

from .models import Question, Choice

#Get Questions and display them
def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)

#Show specific question and choises
def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404('Question does not exists')
    return render(request, 'polls/detail.html', { 'question': question})

#Get question and display results
def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', { 'question': question})

#Vote for a question choice
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        #Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question' : question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

posts/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <title>Someheader App Center {% block title %}{% endblock %}</title>
    </head>
    <body>
        <!-- NavBar -->
        {% include 'partials/_navbar.html' %}
        <div class="container">
            <div class="row">
                <div class="col-md-6 m-auto">
                    {% block content %}{% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>

templates/landing.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Scrolling Nav - Start Bootstrap Template</title>

  <!-- Bootstrap core CSS -->
  <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="css/scrolling-nav.css" rel="stylesheet">

</head>

<body id="page-top">

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand js-scroll-trigger" href="#page-top">Start Bootstrap</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#about">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#services">Services</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#contact">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <header class="bg-primary text-white">
    <div class="container text-center">
      <h1>Welcome to Scrolling Nav</h1>
      <p class="lead">A landing page template freshly redesigned for Bootstrap 4</p>
    </div>
  </header>

  <section id="about">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 mx-auto">
          <h2>About this page</h2>
          <p class="lead">This is a great place to talk about your webpage. This template is purposefully unstyled so you can use it as a boilerplate or starting point for you own landing page designs! This template features:</p>
          <ul>
            <li>Clickable nav links that smooth scroll to page sections</li>
            <li>Responsive behavior when clicking nav links perfect for a one page website</li>
            <li>Bootstrap's scrollspy feature which highlights which section of the page you're on in the navbar</li>
            <li>Minimal custom CSS so you are free to explore your own unique design options</li>
          </ul>
        </div>
      </div>
    </div>
  </section>

  <section id="services" class="bg-light">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 mx-auto">
          <h2>Services we offer</h2>
          <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut optio velit inventore, expedita quo laboriosam possimus ea consequatur vitae, doloribus consequuntur ex. Nemo assumenda laborum vel, labore ut velit dignissimos.</p>
        </div>
      </div>
    </div>
  </section>

  <section id="contact">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 mx-auto">
          <h2>Contact us</h2>
          <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vero odio fugiat voluptatem dolor, provident officiis, id iusto! Obcaecati incidunt, qui nihil beatae magnam et repudiandae ipsa exercitationem, in, quo totam.</p>
        </div>
      </div>
    </div>
  </section>

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Your Website 2019</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Plugin JavaScript -->
  <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

  <!-- Custom JavaScript for this theme -->
  <script src="js/scrolling-nav.js"></script>

</body>

</html>

templates/notebook/detail.html
{% extends 'base.html' %}
{% block content %}
<h1 class="mb-1 text-center">{{ contact.contact_name }}</h1>
<h5 class="mb-5 text-center">{{ contact.register_date }}</h5>

<ul class="list-group mb-5">
    {{ contacttype.contact_type }}
</ul>
<div class="d-flex justify-content-around">
    <a class="btn btn-secondary" href="{% url 'polls:index' %}">Back To Polls</a>
    <a class="btn btn-dark" href="{% url 'polls:detail' contact.id %}">Vote again?</a>
</div>
{% endblock %}

templates/notebook/index.html
{% extends 'base.html' %}
{% block content %}
    <h1 class="text-center mb-3"></h1>
    {% if contacts_list %}
        {% for contact in contacts_list %}
            <div class="card mb-3">
                <div class="card-body">
                    <p class="lead mb-0">{{ contact.contact_name }}</p>
                    <footer class="blockquote-footer mb-3">{{ contact.register_date }}</footer>
                    <a href="{% url 'notebook:detail' contact.id %}" class="btn btn-primary
                    btn-sm">Details</a>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <p>No contacts available</p>
    {% endif %}
{% endblock %}

templates/pages/index.html
<!DOCTYPE html>
<html lang="en">
  
{% load static %}
{% block content %}

<head>
  
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  
  <title>Someheader</title>
  
  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  
  <!-- Custom styles for this template -->
  <link href="{% static 'css/scrolling-nav.css' %}" rel="stylesheet">
  
</head>

<body id="page-top">
  
  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand js-scroll-trigger" href="#page-top">Someheader</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#about">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#services">Portifolio</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#contact">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  
  <header class="bg-primary text-white">
    <div class="container text-center">
      <h1>Welcome to Someheader Portifolio Page</h1>
      <p class="lead">Meet Someheader and the portifolio</p>
    </div>
  </header>
  
  <section id="about">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 mx-auto">
          <h2>About Someheader</h2>
          <p class="lead">Someheader works mainly on Python, financial data oriented and general python works. This is a portifolio made to showcase
            and let know my jobs.
          </p>
          <ul>
            <li>Numpy and Pandas data gettering and analysis, specialised on financial data.</li>
            <li>Django and JavaScript training codes.</li>
          </ul>
        </div>
      </div>
    </div>
  </section>
  
  <section id="services" class="bg-light">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 mx-auto">
          <h2>Portifolio Codes</h2>
          <p class="lead">Below, you can find the codes I've worked on.</p>
          <h3>Django</h3>
          <a href="{% url 'polls:index' %}" class="btn btn-dark">Polls App</a>
          <a href="{% url 'notebook:index' %}" class="btn btn-dark">Notebook App</a>
        </div>
      </div>
    </div>
  </section>

  <section id="contact">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 mx-auto">
          <h2>Contact us</h2>
          <p class="lead">Here we should find some contact informations</p>
        </div>
      </div>
    </div>
  </section>
  
  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Someheader &copy; 2020</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core -->
  <!-- Plugin JavaScript -->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom JavaScript for this theme -->
  <script src="{% static 'js/scrolling-nav.js' %}"></script>

</body>

</html>

{% endblock %}

templates/partials/_navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/">SomeApps</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <div class="navbar-nav navbar-right">
            <a class="nav-item nav-link" href="/polls">Polls App</a>
        </div>
    </div>
</nav>

templates/polls/detail.html
{% extends 'base.html' %}
{% block content %}
<a class="btn btn-secondary btn-sm mb-3" href="{% url 'polls:index' %}">Back To Polls</a>
<h1 class="text-center mb-3">{{ question.question_text }}</h1>

{% if error_message %}
<p class="alert alert_danger">
    <strong>{{ error_message }}</strong>
</p>
{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <div class="form-check">
            <input
                type="radio"
                name="choice"
                class="form-check-input"
                id="choice{{ forloop.counter }}"
                value="{{ choice.id }}"
            >
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
        </div>
    {% endfor %}
    <input type="submit" value="Vote" class="btn btn-success btn-lg btn-block mt-4">
</form>
{% endblock %}

templates/polls/index.html
{% extends 'base.html' %}
{% block content %}
    <h1 class="text-center mb-3"></h1>
    {% if latest_question_list %}
        {% for question in latest_question_list %}
            <div class="card mb-3">
                <div class="card-body">
                    <p class="lead mb-0">{{ question.question_text }}</p>
                    <footer class="blockquote-footer mb-3">{{ question.pub_date }}</footer>
                    <a href="{% url 'polls:detail' question.id %}" class="btn btn-primary
                    btn-sm">Vote Now</a>
                    <a href="{% url 'polls:results' question.id %}" class="btn btn-secondary
                    btn-sm">Results</a>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <p>No polls available</p>
    {% endif %}
{% endblock %}

templates/polls/results.html
{% extends 'base.html' %}
{% block content %}
<h1 class="mb-1 text-center">{{ question.question_text }}</h1>
<h5 class="mb-5 text-center">{{ question.pub_date }}</h5>

<ul class="list-group mb-5">
    {% for choice in question.choice_set.all %}
    <li class="list-group-item">
        {{ choice.choice_text }} <span class="badge badge-success float-right">
            {{ choice.votes }} vote{{ choice.votes | pluralize }}</span>
    </li>
    {% endfor %}
</ul>
<div class="d-flex justify-content-around">
    <a class="btn btn-secondary" href="{% url 'polls:index' %}">Back To Polls</a>
    <a class="btn btn-dark" href="{% url 'polls:detail' question.id %}">Vote again?</a>
</div>
{% endblock %}